### ISSUE TITLE
Typewriter text

### ISSUE THREAD

**Issue by kylebgorman** [CUNY-CL/latin_scansion_webapp#2]
The new style files introduced in #1 provide the same font for `<tt>` tags, used heavily in the About page, as all other text. Is there a compatible, visually appealing monospaced typewriter font we could use for these instead?

**Comment by jillianchang** [comment]
What is a \<tt> tag?

**Comment by kylebgorman** [comment]
`tt` stands for "teletype text": it gives you a monospaced typewriter-style font. I use it for software elements (names of classes, functions, modules, files, etc.) in our about page, but as is it's not rendering any differently than normal body text because of the CSS setup.

CSS reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tt

**Comment by kylebgorman** [comment]
Closed in #10.
